version: "2.1"

networks:
  custom:
    driver: bridge

services:
  worker:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    volumes:
      - .:/go-rmq-worker-tmpl
    depends_on:
      rmq:
        condition: service_healthy
    networks:
      - custom
    ports:
      - 8080:8080

  rmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=pog7x
      - RABBITMQ_DEFAULT_PASS=pass
    networks:
      - custom
    ports:
      - 35672:15672
      - 25672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
