version: "2.1"

networks:
  custom:
    driver: bridge

services:
  worker:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    volumes:
      - .:/go-rmq-worker-tmpl
    depends_on:
      rmq:
        condition: service_healthy
    networks:
      - custom
    ports:
      - "8080:8080"
    environment:
      - RMQ_USER=pog7x
      - RMQ_PASSWORD=pass
      - RMQ_HOST=rmq
      - RMQ_PORT=5672

      - RMQ_VHOST=/

      - RMQ_EXCHANGE=pog7x.go-rmq-worker-tmpl.exchange
      - RMQ_QUEUE=pog7x.go-rmq-worker-tmpl.queue
      - RMQ_ROUTING_KEY=pog7x.go-rmq-worker-tmpl.key

  rmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=pog7x
      - RABBITMQ_DEFAULT_PASS=pass
    networks:
      - custom
    ports:
      - 35672:15672
      - 25672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
